apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  nodeSelector:
    environment: prod
  containers:
  - name: nginx
    image: nginx:latest

#Ho applicato il manifest ma il Pod rimane Pending. Come procedi?